### ISSUE TITLE
Kan ik backup Sonarr converteren naar Medusa?

### ISSUE THREAD

**Issue by Chocka** [BenjV/SYNO-packages#39]
Alhoewel ik probeer Sonarr weer aan de praat te krijgen in DSM7, want daarin staan al mijn settings e.d. Zag ik gisteren Medusa, welke ik inmiddels zonder problemen heb kunnen installeren. Maar wil graag de informatie uit Sonarr backup voortzetten in Medusa, als dat mogelijk is?

**Comment by BenjV** [comment]
Nee dat is onmogelijk.

Wel kun je Medusa de folder waar de videos staan laten scannen en die zullen dan in Medusa geïmporteerd worden.
Zo bouw je de database dan weer gewoon op.

**Comment by Chocka** [comment]
Waar vind een stapsgewijs handleiding? Ben inmiddels de bestaande series aan het toevoegen, maar zie dat ik foutmeldingen krijg?

2021-11-23 21:10:57 ERROR    SHOWQUEUE-REFRESH :: [2f6a130] 282254: Error while refreshing show BoJack Horseman. Error: [Errno 13] Permission denied: '/volume1/Series/BoJack Horseman'
Traceback (most recent call last):
  File "/volume1/@appstore/medusa/src/medusa/queues/show_queue.py", line 514, in run
    self.show.refresh_dir()
  File "/volume1/@appstore/medusa/src/medusa/tv/series.py", line 2048, in refresh_dir
    self.load_episodes_from_dir()
  File "/volume1/@appstore/medusa/src/medusa/tv/series.py", line 1086, in load_episodes_from_dir
    media_files = helpers.list_media_files(self.location)
  File "/volume1/@appstore/medusa/src/medusa/helpers/__init__.py", line 265, in list_media_files
    for cur_file in os.listdir(path):
PermissionError: [Errno 13] Permission denied: '/volume1/Series/BoJack Horseman'

**Comment by BenjV** [comment]
Je moet de system internal user "sc-medusa" lees en schrijfrechten geven op die video folder.

**Comment by Chocka** [comment]
OK aangepast, Medusa is bezig dus even afwachten. 

Had overigens bij de Sonarr issue inmiddels een log weergegeven nadat ik Sonarr opnieuw heb geinstalleerd, waarbij de foutmelding nog niet is veranderd.  

En waar vind een stapsgewijs handleiding voor Medusa?

**Comment by BenjV** [comment]
Kijk eens in de wiki's die op de medusa github zijn te vinden
