### ISSUE TITLE
500 (Internal Server Error)

### ISSUE THREAD

**Issue by hogendoorn** [BenjV/SYNO-packages#9]
When i try to test the Opensubtitles it keeps spinning. If i trace the page to "url:9960/config/testOpenSubtitles?opensubtitlesuser="

![image](https://user-images.githubusercontent.com/12395796/49312860-c97e8400-f4e5-11e8-97fa-259e295a7752.png)

`Traceback (most recent call last):
  File "/volume1/@appstore/autosub/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/volume1/@appstore/autosub/cherrypy/lib/encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/volume1/@appstore/autosub/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/volume1/@appstore/autosub/autosub/WebServer.py", line 415, in testOpenSubtitles
    if OS_Login(opensubtitlesuser,opensubtitlespasswd):
  File "/volume1/@appstore/autosub/autosub/OpenSubtitles.py", line 31, in OS_Login
    OS_logout(Result['token'])
NameError: global name 'OS_logout' is not defined
`

**Comment by BenjV** [comment]
If I see errors as "global name OS_logout is not defined" it tells me that you are missing parts of the installation.

**Comment by hogendoorn** [comment]
Can i check some thinks? perhaps if the function exists somewhere?

**Comment by BenjV** [comment]
I found the problem
On line 31 of the file "/volume1/@appstore/autosub/autosub/OpenSubtitles.py" there is een spelling mistake.
It says OS_logout and it should be OS_Logout with a capital "L".

It only occurrs when you do a test login on Opensubtitles.
I will fix it in the next release so don't use the teest login in the mean time or fix the file yourself.

**Comment by hogendoorn** [comment]
Thanks, that did the trick. 
I have read a dutch post on a other forum there has been a big API change for OpenSubtitles. Is that the reason why AutoSub won't find much a.t.m?
